# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noenvy < Formula
  desc "Encrypt .env files with your OS keyring and inject secrets into any command."
  homepage "https://github.com/matthewdtowles/noenvy"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthewdtowles/noenvy/releases/download/v0.0.2/noenvy_0.0.2_darwin_x86_64.tar.gz"
      sha256 "b8399c82354afbb42b06341e587d73f14402403d1f8b48037dc90d11812de5f3"

      define_method(:install) do
        bin.install "noenvy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthewdtowles/noenvy/releases/download/v0.0.2/noenvy_0.0.2_darwin_arm64.tar.gz"
      sha256 "e4a64feb523f54884531b06d657f9645c3b063ccccd3ece38566c09fca3eec0d"

      define_method(:install) do
        bin.install "noenvy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthewdtowles/noenvy/releases/download/v0.0.2/noenvy_0.0.2_linux_x86_64.tar.gz"
      sha256 "b7963d6648cd45db2ca4c6b6f6a2764884df3f49adaf3ccaaa34b82920428f67"
      define_method(:install) do
        bin.install "noenvy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthewdtowles/noenvy/releases/download/v0.0.2/noenvy_0.0.2_linux_arm64.tar.gz"
      sha256 "6a80bfa3ad1e3dfb3f92348ad91eff7d76bda22ec7cf0f1d68ce981e420134a3"
      define_method(:install) do
        bin.install "noenvy"
      end
    end
  end

  test do
    system "#{bin}/noenvy", "-v"
  end
end
