# This file was generated by GoReleaser. DO NOT EDIT.
cask "noenvy" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "332824c6990678ff9f769c8de5a7bbfc38a1729fdefc6d643abb59dd945d0938"
      url "https://github.com/matthewdtowles/noenvy/releases/download/v#{version}/noenvy_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "75ec2de76bdd7b04e253ffccad3356e6dc808f57e79d92784cefc4da482c8b44"
      url "https://github.com/matthewdtowles/noenvy/releases/download/v#{version}/noenvy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db19dfb333868bf5664c8a185b65e06ac1574995016d55e9cf6656d008a360ac"
      url "https://github.com/matthewdtowles/noenvy/releases/download/v#{version}/noenvy_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bc1b65b065221ee6b64b79d2c250e59111e94a338dd08e864a5c0bb9130cc02d"
      url "https://github.com/matthewdtowles/noenvy/releases/download/v#{version}/noenvy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noenvy"
  desc "Encrypt .env files with your OS keyring and inject secrets into any command."
  homepage "https://github.com/matthewdtowles/noenvy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noenvy"

  # No zap stanza required

end
